version: 2

title: Recipes
url: "https://recipes.jbmorley.co.uk"

port: 8001

steps:
  - when: '(.*/)?\.DS_Store'
    then: ignore
  - when: '(.*/)?\..*'
    then: ignore
  - when: '(.*/)?.*~'
    then: ignore
  - when: '.*\.(markdown|md)'
    then: markdown
    args:
        defaultCategory: recipes
        defaultTemplate: page.html
  - when: 'snapshots.*\.(jpg|jpeg|png|gif|tiff|heic)'
    then: image
    args:
        category: photos
        titleFromFilename: False
        defaultTemplate: photo.html
        inlineTemplate: image.html
  - when: '.*'
    then: copy
