name: build-and-deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ build ]

jobs:
  run:

    runs-on: macos-13

    steps:

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive

    - name: Build site
      run: |
        cd site
        scripts/build.sh

#     - name: Deploy site
#       if: github.ref == 'refs/heads/main'
#       env:
#         ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
#       run: |
#         cd site
#         ./ansible/deploy.py
